from pathlib import Path
import html,json
ROOT=Path(__file__).resolve().parents[1]
D=ROOT/'docs-src'
CSS='''@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;color:#243329;font-family:Arial,"Apple SD Gothic Neo",sans-serif;font-size:13px;line-height:1.7}section.page{width:210mm;height:297mm;padding:18mm 18mm 16mm;position:relative;break-after:page;overflow:hidden}.kicker{font-size:10px;letter-spacing:2px;color:#42664c;font-weight:700;border-top:3px solid #294c37;padding-top:12px}h1{font-size:34px;line-height:1.3;letter-spacing:-1.2px;margin:25px 0 17px}h2{font-size:22px;line-height:1.4;margin:22px 0 15px}h3{font-size:15px;margin:20px 0 6px}p{margin:9px 0;word-break:keep-all;overflow-wrap:anywhere}.lead{font-size:16px;color:#59675a}.box{padding:16px 19px;background:#edf2e4;border-radius:10px;margin:18px 0}.small{font-size:10px;color:#647060}.foot{position:absolute;bottom:10mm;left:18mm;right:18mm;border-top:1px solid #d3dbce;padding-top:6px;font-size:9px;color:#667260;display:flex;justify-content:space-between}table{width:100%;border-collapse:collapse;margin:16px 0;font-size:11px;table-layout:fixed}th{background:#e9efdf;text-align:left}td,th{padding:9px 10px;border-bottom:1px solid #d9dfd4;vertical-align:top;overflow-wrap:anywhere}th:first-child{width:27%}ul,ol{padding-left:21px}li{margin:7px 0}code{font-family:Menlo,monospace;font-size:11px;background:#edf0e8;padding:1px 4px}pre{white-space:pre-wrap;word-break:break-word;background:#243329;color:#f1f5e9;padding:15px;border-radius:8px;font-size:10px;line-height:1.7}pre code{background:none;color:inherit;padding:0;font-size:10px}.figure{position:relative;margin:18px 0 8px;border:1px solid #d4dbcd;background:#f7f8f3;border-radius:8px;overflow:hidden}.figure img{display:block;width:100%}.figure .pin{position:absolute;border-radius:50%;background:#294c37;color:white;border:2px solid white;box-shadow:0 2px 7px #0003;width:27px;height:27px;text-align:center;line-height:23px;font-size:12px;font-weight:bold}.caption{font-size:10px;color:#647060;margin:6px 0 15px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:18px}.mobile{display:grid;grid-template-columns:190px 1fr;gap:24px;align-items:start}.mobile .figure{margin-top:0}.flow{padding:14px;background:#294c37;color:white;border-radius:8px;text-align:center;font-size:13px;margin:15px 0}a{color:#2a6041;text-decoration:underline} .strip img{max-height:225px;object-fit:contain}.cover-index{margin-top:40px}'''
def table(rows,heads=('개념 / 항목','쉽게 이해하기 · 실제 적용')):
 return '<table><tr>'+''.join('<th>'+x+'</th>' for x in heads)+'</tr>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in r)+'</tr>' for r in rows)+'</table>'
def box(s):return '<div class="box">'+s+'</div>'
def code(s):return '<pre><code>'+html.escape(s)+'</code></pre>'
def fig(name,caption,pins=[],cls=''):
 src='../deliverables/screenshots/'+name
 return f'<div class="figure {cls}"><img src="{src}">'+''.join(f'<span class="pin" style="left:{x}%;top:{y}%">{i}</span>' for i,x,y in pins)+f'</div><p class="caption">{caption}</p>'
def doc(filename,title,pages):
 content=''.join(f'<section class="page"><div class="kicker">FIRST WEB / {title}</div>{s}<div class="foot"><span>나를 소개하는 웹페이지 · 초보자를 위한 학습 예시</span><span>{i+1:02} / {len(pages):02}</span></div></section>' for i,s in enumerate(pages))
 (D/(filename+'.html')).write_text(f'<!doctype html><html lang="ko"><meta charset="utf-8"><title>{title}</title><style>{CSS}</style><body>{content}</body></html>')

pages=[]
pages.append('''<h1>과제 내용 파악하기</h1><p class="lead">처음 배우는 사람을 위한<br>“무엇을, 왜, 어디까지 만들어야 할까?”</p>'''+fig('02-hero.png','이번 작업에서 실제 제작한 가상 인물 김하늘의 포트폴리오 화면.')+box('<b>중학생 수준으로 말하면</b><p>나를 소개하는 온라인 전시장을 만드는 과제입니다. 글과 사진을 놓고, 휴대폰에서도 잘 보이게 꾸미고, 버튼을 누르면 화면이 바뀌도록 만듭니다. GitHub라는 코드 보관소에서 작품 목록도 가져옵니다.</p>')+'''<h3>이 문서에서 확인할 것</h3><ol><li>과제의 목적과 필수 결과물</li><li>원문 요구사항과 예시 구현의 대응</li><li>알아야 할 개념 목차와 추천 학습 순서</li><li>예시 실행 방법과 실제 제출 전 남은 작업</li></ol><p class="small">기준 자료: 사용자가 지정한 「나를 소개하는 웹페이지 처음부터 만들기.pdf」 전체 9쪽. 원문의 지시를 과제 요구사항으로 분석했으며, 계정 연결이나 공개 게시를 별도로 실행하라는 사용자 지시로 해석하지 않았습니다.</p>''')
pages.append('<h1>무엇을 만드는 과제인가?</h1><p class="lead">HTML은 내용, CSS는 모습, JavaScript는 행동을 맡습니다.</p>'+table([
('HTML · 뼈대','제목, 자기소개, 기술 목록, 프로젝트, 문의 폼에 의미와 순서를 부여합니다. 예: <code>&lt;h1&gt;</code>은 가장 중요한 제목입니다.'),('CSS · 꾸미기','글자 색, 여백, 카드 배치, 화면 크기별 모양을 결정합니다. 예: 넓은 화면의 카드 여러 열이 좁은 화면에서는 한 열이 됩니다.'),('JavaScript · 동작','클릭과 입력을 감지하고 화면을 바꿉니다. 예: 다크 모드 버튼을 누르면 색상 묶음을 교체합니다.'),('GitHub API · 자료 요청','외부 서비스에 공개 저장소 목록을 요청해 카드로 바꿉니다. 인터넷이 느리거나 실패해도 상황을 알려야 합니다.'),('GitHub Pages · 공개 주소','완성한 파일을 인터넷에서 열 수 있도록 게시합니다. 내 컴퓨터에서만 열리는 파일과 공개 URL은 다릅니다.')])+ '<h2>겉모습보다 중요한 한 줄</h2><div class="flow">사용자 이벤트 → 상태 변경 → DOM 업데이트 → 화면 변화</div>'+box('<b>예: 방의 전등 스위치</b><p>스위치를 누르는 행동은 이벤트, 불이 켜졌는지는 상태, 방이 밝아지는 것은 화면 변화입니다. 웹에서는 버튼 클릭, theme 값, CSS 적용이 각각 그 역할을 합니다.</p>')+'<h3>과제의 학습 조건</h3><p>원문은 80시간 학습 과제입니다. React, Vue, jQuery, Bootstrap, Tailwind 같은 외부 라이브러리 없이 순수 HTML/CSS/JavaScript로 구현합니다. 이번 웹도 실행용 외부 라이브러리를 사용하지 않습니다.</p><p class="small">원문 근거: 1~2쪽(목표·결과물), 7쪽(환경·제약). PDF 및 캡처 제작 도구는 웹 실행 코드와 별도입니다. 원문의 “브라우저가 이해하는 유일한 언어” 표현은 입문용 단순화이며, 여기서는 웹 프론트엔드의 핵심 세 기술로 이해합니다.</p>')
pages.append('<h1>필수 요구사항 대조표</h1>'+table([
('기본 구조<br>원문 2~3쪽','<b>구현</b> · index.html, css/style.css, js/main.js, images/. 외부 CSS 연결, JS의 defer, 6개 필수 섹션.'),('HTML<br>원문 3쪽','<b>구현</b> · header/nav/main/section/article/footer, 앵커, 프로필 alt, label의 for-id 연결.'),('CSS<br>원문 3~4쪽','<b>구현</b> · :root 변수, 다크 테마 변수, 메뉴 Flexbox, 카드 Grid의 auto-fit/minmax, 768/1024px 분기, hover/transition/shadow.'),('이벤트·문법<br>원문 4~5쪽','<b>구현</b> · const/let, querySelector/All, addEventListener, click/submit/scroll/input, textContent/innerHTML, classList, 화살표 함수·구조분해·map/forEach.'),('인터랙션<br>원문 4~5쪽','<b>구현</b> · 햄버거, 부드러운 스크롤, 300px 맨 위 버튼, 60px 메뉴 배경, 테마 저장, Observer threshold 0.2.'),('폼·상태<br>원문 5~6쪽','<b>구현</b> · 필수값/이메일 검사, 필드 근처 오류, preventDefault, 성공 안내. 테마·API·폼의 상태→렌더링.'),('GitHub API<br>원문 5~6쪽','<b>예시 구현</b> · fetch, async/await, try/catch와 4개 상태. 실제 연결은 octocat 공개 예시 계정. 본인 계정으로 교체 필요.'),('개발·배포·제출<br>원문 3·6~7쪽','<b>남은 단계</b> · VS Code + Live Server의 학습자 환경 구성, 본인 저장소 URL, GitHub Pages 배포 URL. 이번 결과물은 로컬 예시이며 공개 배포하지 않았습니다.')])+box('<b>선택 구현과 미구현</b><p>언어 필터(filter)는 구현했습니다. 학습 실험실은 이해를 돕기 위한 추가 기능입니다. 타이핑 효과, 실제 메일 전송, 시스템 테마 자동 감지는 구현하지 않았으며 원문에서도 선택 항목입니다.</p>'))
pages.append('<h1>필수 개념 목차와 학습 순서</h1><p>코드를 모두 외우기보다, 각 단계에서 작은 변경을 직접 하고 결과를 설명하는 것이 목표입니다.</p>'+table([
('① 파일과 실행','폴더, 확장자, 상대 경로, 브라우저, 편집기, Live Server. → index.html을 열고 소개 문장 하나를 바꾸기.'),('② HTML의 의미','태그, 속성, 제목 단계, 시맨틱 구조, 앵커, alt, label. → 메뉴 링크가 가리키는 section의 id 찾기.'),('③ CSS와 반응형','선택자, 상속·우선순위, 박스 모델, 변수, Flex/Grid, 미디어 쿼리. → 카드 간격과 화면 너비를 바꿔보기.'),('④ JavaScript 기초','const/let, 문자열, 객체, 배열, 함수, 조건, 템플릿, 구조분해. → 프로젝트 설명을 수정하고 카드 확인하기.'),('⑤ DOM·이벤트·상태','요소 선택, 이벤트 리스너, classList, 상태와 렌더링, 기본 동작 취소. → 테마 버튼의 클릭 흐름을 말로 설명하기.'),('⑥ 비동기와 예외','JSON, Promise의 기초, fetch, async/await, HTTP 상태, try/catch. → 로딩/성공/오류/빈 상태를 각각 재현하기.'),('⑦ 품질과 제출','폼 검증, 저장소, 접근성, 외부 데이터 처리, 콘솔·Network, Git/GitHub/Pages 구분. → 모바일 검사 후 본인 정보로 교체하고 배포하기.')])+ '<h2>80시간을 나누는 예시 계획</h2><p>환경과 과제 분석 6h → HTML 10h → CSS/반응형 16h → JS/DOM 18h → API와 폼 16h → 검증/배포/회고 14h. 시간 배분은 이 안내서의 제안이며 원문이 지정한 세부 시간표는 아닙니다.</p>'+box('<b>AI에게 요청한 뒤 내가 확인할 것</b><p>“다크 모드가 만들어졌어”에서 멈추지 말고, 이벤트가 붙은 줄·바뀌는 상태·화면에 반영하는 줄을 찾아 설명해 보세요. 코드 생성 결과는 이해했다는 증거가 아니므로 직접 실험한 내용을 한 문장으로 기록합니다.</p>'))
pages.append('<h1>예시 실행과 제출 준비</h1><h2>지금 예시를 보는 방법</h2><ol><li><b>portfolio/index.html</b>을 브라우저에서 엽니다. 기본 예시 카드와 모든 로컬 인터랙션을 사용할 수 있습니다.</li><li>과제와 같은 개발 흐름은 VS Code에서 portfolio 폴더를 열고 Live Server로 index.html을 실행하는 것입니다. 저장 후 화면이 갱신되는지 확인합니다.</li><li>Projects의 데이터 선택을 <b>GitHub 실제 연결</b>로 바꾸면 인터넷으로 octocat의 공개 저장소를 요청합니다.</li><li>학습 실험실에서 로딩·에러·빈 상태를 확인하고, 문의 폼에 빈 값이나 잘못된 이메일을 입력해 봅니다.</li></ol><h2>실제 과제로 제출하려면</h2><ol><li>가상 이름·소개·일러스트를 본인 내용으로 교체합니다.</li><li>js/main.js의 <code>GITHUB_USERNAME</code>과 HTML의 안내 문구·GitHub 링크를 본인 계정에 맞춥니다. 제출본은 실제 API 연결을 기본값으로 바꾸는 것이 좋습니다.</li><li>별도 GitHub 저장소의 최상위에 portfolio 폴더 <b>안의 파일</b>을 올립니다. index.html이 저장소 루트에 있게 합니다.</li><li>저장소 Settings → Pages에서 게시 원본을 해당 브랜치와 /(root)로 지정합니다. 생성된 URL을 README에 기입합니다.</li><li>공개 URL에서 반응형, API, 테마, 폼을 다시 검사하고 데스크톱·모바일·다크 화면을 함께 제출합니다.</li></ol>'+box('<b>현재 완료 범위</b><p>웹 예시, 학습 PDF 3종, 실제 화면 캡처, 기능 검증이 포함됩니다. 본인 계정 적용·개인 환경 설정·공개 배포는 완료되지 않았습니다. 문의 폼은 입력 검증만 하며 메시지를 전송하지 않습니다.</p>')+'<p class="small">공식 참고: <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site">GitHub Pages 게시 원본 설정</a>. UI나 권한에 따라 설정 경로가 다를 수 있습니다. 기본 개념의 다음 단계는 「개념 4단계」, 화면별 설명은 「실전 개념 적용」을 읽으세요.</p>')
doc('01-assignment','과제 내용 파악',pages)

levels=[
('1단계','기초적으로 알아야 하는 개념','코드를 읽기 위한 언어를 준비합니다.',[
('파일·경로','폴더는 서랍, 파일은 그 안의 종이입니다. 상대 경로는 현재 파일을 기준으로 찾는 주소입니다.','index.html의 css/style.css 연결','CSS 파일명을 바꾸면 꾸밈이 사라지는 이유를 설명한다.'),
('HTML 태그·속성','태그는 내용의 종류, 속성은 추가 설명입니다. h1은 큰 제목, href는 이동 주소입니다.','h1, a href="#projects"','href와 대상 id가 같아야 이동함을 확인한다.'),
('CSS 선택자·박스 모델','선택자는 꾸밀 대상, padding은 안쪽 여백, margin은 바깥 여백입니다.',' .button, .section, box-sizing','버튼 padding을 키워 글자는 같아도 버튼이 커짐을 본다.'),
('변수·값·조건','변수는 이름 붙인 값입니다. const는 재할당 금지, let은 재할당 가능입니다.','state 객체, requestVersion 변수','const 객체의 속성은 바뀔 수 있음을 구분한다.'),
('함수·객체·배열','함수는 재사용할 일, 객체는 한 대상의 정보, 배열은 순서 있는 목록입니다.','samples 배열의 프로젝트 객체, renderTheme 함수','name은 카드 한 개의 속성이고 samples는 목록임을 말한다.')]),
('2단계','필수적으로 알아야 하는 개념','과제의 주요 기능을 스스로 따라가 봅니다.',[
('시맨틱 HTML','의미 있는 영역 이름입니다. nav는 길 안내, main은 주요 내용입니다.','header/nav/main/section/article/footer','article과 section을 사용한 기준을 말한다.'),
('Flexbox·Grid·반응형','Flex는 한 방향 정렬, Grid는 행과 열 배치에 편합니다. 반응형은 화면 너비에 맞춘 조절입니다.','메뉴 Flex, 프로젝트 Grid, 768/1024px','모바일 한 열과 데스크톱 여러 열의 차이를 설명한다.'),
('DOM·이벤트·렌더링','DOM은 브라우저가 만든 요소 구조, 이벤트는 발생한 행동, 렌더링은 상태를 화면에 반영하는 과정입니다.','querySelector, addEventListener, renderTheme','클릭 → theme 변경 → data-theme 반영을 찾는다.'),
('ES6+·배열 메서드','화살표 함수는 함수 문법, 구조분해는 속성 꺼내기입니다. map은 변환, filter는 선별, forEach는 순회입니다.','renderProjects의 filter → map → join','CSS 필터가 원본 목록을 지우지 않는 이유를 말한다.'),
('비동기·API·JSON','API는 데이터 요청 규칙, JSON은 데이터를 담는 형식입니다. await는 비동기 작업의 결과를 기다립니다.','loadProjects의 fetch와 response.json()','기다리는 동안에도 메뉴 클릭이 가능한 이유를 말한다.'),
('폼·저장·상태','입력 검사 결과와 테마 선택도 상태입니다. localStorage는 브라우저에 값을 보관합니다.','validate, preventDefault, localStorage','입력 오류를 고치면 에러가 사라지고 테마는 새로고침 후 유지됨을 확인한다.')]),
('3단계','모르면 나중에 곤란한 개념','문제가 생겼을 때 고치고, 사용자를 배려합니다.',[
('HTTP 오류·예외','fetch는 404/403 응답만으로 자동 실패하지 않습니다. response.ok를 확인해야 합니다.','loadProjects의 !response.ok와 try/catch','존재하지 않는 계정과 요청 제한도 오류 화면으로 안내한다.'),
('접근성','키보드나 화면 읽기 도구로도 사용할 수 있어야 합니다. label, alt, 초점, aria가 돕습니다.','label for-id, aria-expanded, aria-live, :focus-visible','Tab으로 버튼에 접근하고 오류 난 첫 입력으로 초점이 이동하는지 본다.'),
('외부 데이터·XSS','외부 문자열을 HTML로 그대로 넣으면 악성 코드로 해석될 수 있습니다. 텍스트로 처리하거나 이스케이프합니다.','escapeHTML, safeRepoURL, textContent','프로젝트 설명의 < 문자가 태그로 실행되지 않는지 확인한다.'),
('디버깅·CSS 우선순위','콘솔은 실행 오류, Network는 요청 결과를 보여줍니다. CSS는 더 구체적인 규칙 등이 우선합니다.','테마 선택자와 공통 변수; 개발자 도구','색이 안 바뀌면 적용된 스타일과 선택자를 먼저 확인한다.'),
('검증과 전송의 차이','브라우저 검증은 UX 보조입니다. 실제 전송 서비스는 서버에서도 검증해야 합니다.','폼 성공 안내에 실제 미전송 명시','성공 문구가 곧 이메일 발송 증거는 아님을 설명한다.'),
('Git·GitHub·배포','Git은 변경 기록 도구, GitHub는 저장·협업 서비스, Pages는 웹 게시 기능입니다.','로컬 파일과 공개 사이트 URL','내 컴퓨터 경로를 다른 사람에게 줘도 열 수 없음을 이해한다.')]),
('4단계','몰라도 되지만 알면 더 깊이 보이는 개념','기본 기능을 설명한 뒤 확장합니다.',[
('요청 경쟁·취소','먼저 시작한 요청이 나중에 도착하면 최신 화면을 덮을 수 있습니다. 오래된 요청을 무시하거나 취소합니다.','requestVersion, AbortController, 12초 타임아웃','API 대기 중 예시로 바꿔도 예시가 유지되는 원리를 이해한다.'),
('관찰자·움직임 배려','Intersection Observer는 요소가 보이는 정도를 관찰합니다. reduced-motion은 움직임을 줄이라는 사용자 설정입니다.','threshold:0.2, prefers-reduced-motion','관찰 대상의 약 20%가 보이면 나타나는 효과를 적용한다.'),
('점진적 향상','기본 내용을 먼저 제공하고 지원되는 기능을 더합니다. JS가 실패해도 소개 내용은 남게 설계합니다.','Observer 지원 검사, HTML의 정적 소개','JS가 없으면 기본 소개는 남지만 카드·검증은 작동하지 않음을 구분한다.'),
('디자인 토큰','색·간격·반경에 이름을 붙여 여러 곳에서 공유하는 설계 방식입니다.','--bg, --accent, --radius','테마 하나를 바꾸면 여러 요소가 함께 바뀌는 이유를 말한다.'),
('페이지네이션·캐시','많은 데이터를 나눠 받거나 이전 응답을 재사용하는 방식입니다.','현재 per_page=100; 추가 페이지·캐시는 미구현','저장소가 100개보다 많을 때 모든 목록을 받으려면 확장이 필요함을 안다.')])]
pages=['<h1>개념을 4단계로 나누기</h1><p class="lead">암기 순서가 아니라,<br>만들고 설명할 수 있는 범위를 넓히는 지도입니다.</p>'+table([(a+'<br>'+b,c) for a,b,c,_ in levels])+box('<b>단계는 이 안내서에서 정한 학습 기준입니다.</b><p>3단계도 실제 제출 품질에는 중요합니다. 4단계에 설명한 Observer의 내부 동작은 심화지만, 스크롤 애니메이션 구현 자체는 원문의 필수입니다. 단계가 높다고 과제 요구사항을 생략해도 되는 뜻은 아닙니다.</p>')+'<h2>모든 개념에 적용할 학습법</h2><ol><li><b>정의:</b> 친구에게 쉬운 말로 한 문장 설명합니다.</li><li><b>찾기:</b> 예시 웹의 파일과 화면에서 해당 부분을 찾습니다.</li><li><b>변경:</b> 숫자·문구·조건 중 한 가지만 바꿔 봅니다.</li><li><b>검증:</b> 예상과 실제가 같은지 보고 이유를 기록합니다.</li></ol><p>AI에게는 “전체를 다시 만들어줘”보다 “이 버튼의 이벤트·상태·화면 업데이트를 코드 위치와 함께 설명해줘”처럼 작은 범위의 설명을 요청하면 배운 내용을 확인하기 쉽습니다.</p>']
for n,title,intro,items in levels:
 pages.append(f'<h1>{n}<br>{title}</h1><p class="lead">{intro}</p>'+table([(f'<b>{name}</b>',f'{meaning}<br><b>적용:</b> {where}<br><b>확인:</b> {test}') for name,meaning,where,test in items])+('<p class="small">API 오류와 인증 없는 기본 요청 제한(시간당 60회)은 <a href="https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api">GitHub 공식 문서</a> 참고. 반복 새로고침 대신 학습 실험실로 상태를 재현할 수 있습니다.</p>' if n=='3단계' else ''))
pages.append('<h1>내가 이해했는지 확인하기</h1>'+table([
('1단계 실습','소개 제목을 바꾸고 버튼의 padding을 12px에서 18px로 바꿉니다. <b>예상:</b> 문구와 버튼 크기만 달라집니다.'),('2단계 실습','CSS 언어 필터를 누릅니다. <b>예상:</b> 예시 카드 3개 중 CSS 카드 1개만 보입니다. filter가 선택하고 map이 카드로 바꿉니다.'),('3단계 실습','문의 폼을 비운 채 확인합니다. <b>예상:</b> 필드 옆 오류 3개, 첫 오류 필드로 초점 이동. 빈칸에 공백만 넣어도 통과하면 안 됩니다.'),('4단계 실습','GitHub 연결 직후 예시 데이터로 전환합니다. <b>예상:</b> 늦은 실제 응답이 예시 카드를 덮어쓰지 않습니다.')])+ '<h2>자주 섞이는 개념</h2>'+table([('HTML ≠ DOM','HTML은 작성한 문서이고 DOM은 브라우저가 문서를 읽어 만든 조작 가능한 구조입니다.'),('class ≠ id','class는 여러 요소를 묶는 이름, id는 페이지에서 한 요소를 식별하는 이름입니다.'),('map ≠ forEach','map은 반환값들을 새 배열로 만들고, forEach는 순회 작업을 합니다. forEach 결과로 카드 배열을 만들 수는 없습니다.'),('로컬 저장 ≠ 서버 저장','localStorage는 해당 브라우저·출처에 저장합니다. 다른 기기로 자동 동기화되지 않고 삭제되거나 저장이 제한될 수 있습니다.'),('await ≠ 전체 화면 정지','비동기 함수의 다음 처리를 기다립니다. 네트워크 대기 중 브라우저의 다른 상호작용까지 멈추는 것은 아닙니다.')])+box('<b>학습 기록 예시</b><p>오늘 배운 것: DOM 선택과 이벤트.<br>적용 위치: theme-toggle과 renderTheme.<br>내가 바꾼 것: 다크 모드의 배경 변수.<br>확인한 결과: 클릭 직후 배경이 바뀌고 새로고침 후에도 유지됐다.<br>남은 질문: 저장이 차단되면 어떻게 작동할까?</p>'))
doc('02-concepts','개념 4단계',pages)

pages=[]
pages.append('<h1>실전에서 개념 찾기</h1><p class="lead">실제 만든 화면 → 표시 번호 → 코드 → 직접 실험</p>'+fig('02-hero.png','실제 브라우저 캡처에 설명용 번호를 덧붙였습니다. 웹에는 이 번호가 표시되지 않습니다.',[(1,3,25),(2,6,68),(3,75,30)])+table([('① 제목과 소개','HTML의 h1, p. 내용의 의미와 읽는 순서를 결정합니다.'),('② 프로젝트 버튼','a href="#projects". 목적지 section의 id로 이동하고 CSS scroll-behavior가 이동을 부드럽게 합니다.'),('③ 오른쪽 그래픽','CSS의 background, border-radius, gradient, position으로 만든 장식입니다. 이미지를 내려받는 대신 코드로 그립니다.')])+box('<b>읽는 순서</b><p>1. 현재 페이지에서 전체 연결을 봅니다.<br>2. 다음 페이지부터 구조·배치·테마·API·폼을 하나씩 관찰합니다.<br>3. 표의 파일명과 함수명을 검색해 원본 코드와 연결합니다.</p>'))
pages.append('<h1>01. HTML에 의미 붙이기</h1>'+fig('03-about.png','About 영역: 프로필은 직접 제작한 SVG 일러스트이며 실제 인물 사진이 아닙니다.',[(1,2,4),(2,7,45),(3,55,45)])+table([('① section','index.html의 section id="about". 소개 영역이라는 묶음과 메뉴가 이동할 목적지를 만듭니다.'),('② img + alt','images/profile.svg를 표시합니다. alt는 이미지가 보이지 않거나 화면 읽기 도구를 사용할 때 뜻을 전달합니다.'),('③ h3 + p','소제목과 본문을 구분합니다. 글자 크기만 크게 만드는 것과 HTML의 의미를 부여하는 것은 다릅니다.')])+code('<section id="about" class="wrap section reveal">\n  ...\n  <img src="images/profile.svg"\n       alt="가상 인물 김하늘을 나타내는 웃는 얼굴 일러스트">\n  ...\n</section>')+box('<b>직접 해보기</b><p>메뉴의 href="#about"은 그대로 두고 section의 id를 다른 이름으로 바꿔보세요. 연결이 깨집니다. 두 값이 일치해야 한다는 것을 확인한 뒤 복원하세요.</p>'))
pages.append('<h1>02. Flex와 Grid, 반응형</h1>'+fig('04-projects.png','데스크톱 Projects 영역. 메뉴/필터는 Flex, 카드 목록은 Grid로 배치했습니다.',[(1,4,29),(2,8,63),(3,69,63)])+code('.nav { display: flex; align-items: center; }\n.project-grid {\n  display: grid;\n  grid-template-columns:\n    repeat(auto-fit, minmax(min(100%, 280px), 1fr));\n  gap: 20px;\n}')+table([('① 한 방향 정렬','필터 버튼은 Flex로 나란히 놓고 공간이 부족하면 줄바꿈합니다. 상단 nav도 Flex를 사용합니다.'),('②③ 여러 카드 배치','Grid는 들어갈 수 있는 열 개수를 auto-fit으로 정하고 남은 폭을 1fr로 나눕니다. 최소 폭은 280px이지만 작은 컨테이너에서는 100%를 넘지 않게 합니다.')])+box('<b>직접 해보기</b><p>브라우저 폭을 390 → 768 → 1440px로 늘려보세요. 카드 열 개수는 사용 가능한 폭에 따라 바뀝니다. 메뉴 전환은 별도의 768px 미디어 쿼리로 결정됩니다.</p>'))
pages.append('<h1>03. 모바일 메뉴와 스크롤</h1><div class="mobile">'+fig('10-mobile-menu.png','390px 너비의 실제 메뉴 열린 화면.',[(1,76,2),(2,14,14)])+'<div><h3>① 햄버거 버튼</h3><p>클릭을 감지해 메뉴의 active 클래스를 토글합니다. aria-expanded도 동시에 바꿔 열림 상태를 전달합니다.</p><h3>② 메뉴 링크</h3><p>각 section으로 이동한 뒤 메뉴를 닫습니다. Escape 키로도 닫을 수 있습니다.</p><h3>화면을 아래로 내려보세요</h3><p>60px부터 헤더 배경이 바뀝니다. 300px부터 오른쪽 아래에 맨 위 버튼이 나타납니다.</p><p>css/style.css의 @media(min-width:768px)에서 메뉴를 가로 배치하고 햄버거를 숨깁니다.</p></div></div>'+code("$('#menu-toggle').addEventListener('click', () => {\n  const opened = $('#nav-links').classList.toggle('active');\n  $('#menu-toggle').setAttribute('aria-expanded', String(opened));\n  // 버튼의 접근 가능한 이름도 함께 변경\n});")+box('<b>학습 포인트</b><p>classList.toggle의 반환값은 클래스가 적용되었는지 알려줍니다. 메뉴에서는 그 결과를 열림 상태로 사용합니다. 스크롤 효과는 onScroll 함수, 등장 효과는 IntersectionObserver가 담당합니다.</p>'))
pages.append('<h1>04. 다크 모드와 상태 저장</h1><div class="cols"><div>'+fig('01-desktop.png','라이트 모드 전체 화면.',[],'strip')+'</div><div>'+fig('07-dark.png','다크 모드 전체 화면.',[],'strip')+'</div></div><div class="flow">클릭 → state.theme → renderTheme() → CSS 변수 변경</div>'+code("state.theme = state.theme === 'light' ? 'dark' : 'light';\nrenderTheme();\ntry {\n  localStorage.setItem('portfolio-theme', state.theme);\n} catch { /* 현재 페이지에서는 유지 */ }")+table([('클릭 감지','main.js의 theme-toggle 이벤트 리스너. 실행의 시작점입니다.'),('상태 변경','state.theme은 light 또는 dark입니다. 색 자체가 아니라 현재 선택을 저장합니다.'),('화면 반영','renderTheme이 html의 data-theme을 바꿉니다. CSS의 [data-theme="dark"] 변수들이 적용됩니다.'),('다음 방문에 복원','시작할 때 localStorage.getItem으로 읽습니다. 저장 실패도 try/catch로 처리하여 페이지가 멈추지 않게 합니다.')])+box('<b>직접 해보기</b><p>다크 모드 → 새로고침 → 유지 여부 확인. 이어서 CSS의 다크 모드 --bg 값을 바꿔보세요. “저장된 것은 색 코드가 아니라 테마 이름”임을 설명해 보세요.</p>'))
pages.append('<h1>05. 데이터에서 카드로</h1>'+fig('12-live-api.png','실제 GitHub API 연결 결과. 촬영 당시 octocat 공개 저장소 8개를 받았습니다. 본인 프로젝트가 아닙니다.',[(1,78,35),(2,5,65)])+'<p>① 데이터 선택에서 실제 연결을 고르면 loadProjects가 실행됩니다. ② 응답 배열을 state.repos에 저장하고 renderProjects가 카드를 생성합니다.</p>'+code('const response = await fetch(\n  `https://api.github.com/users/${encodeURIComponent(GITHUB_USERNAME)}/repos?sort=updated&per_page=100`,\n  { signal: controller.signal, headers: { Accept: \'application/vnd.github+json\' } }\n);\n// HTTP 성공 여부를 검사한 후\nconst data = await response.json();')+'<p><b>코드 위치:</b> js/main.js의 loadProjects, renderProjects, escapeHTML. map의 결과를 join(\'\')으로 합쳐 innerHTML에 넣습니다. 외부 문자열은 이스케이프하고 링크는 GitHub HTTPS 주소인지 검사합니다.</p>'+box('<b>기본 화면과 실제 연결의 차이</b><p>기본 카드 3개는 학습용 가상 데이터입니다. 실제 연결은 인터넷이 필요하며 최근 공개 저장소 최대 100개만 요청합니다. 언어 필터는 서버 재요청 없이 받아온 배열을 filter로 걸러냅니다.</p>'))
pages.append('<h1>06. 기다림과 실패도 화면이다</h1>'+fig('08-loading.png','① 로딩 상태를 학습 실험실에서 재현한 실제 화면입니다.',[(1,4,45)],'strip')+ '<div class="cols"><div>'+fig('08-error.png','② 오류 상태: 안내와 재시도 버튼.',[],'strip')+'</div><div>'+fig('08-empty.png','③ 빈 상태: 정상 결과가 0개일 때.',[],'strip')+'</div></div>'+table([('① loading','요청을 시작할 때 즉시 표시합니다. 카드는 비우고 aria-busy를 true로 설정합니다.'),('② error','네트워크 실패, HTTP 실패, 12초 초과 등을 안내합니다. 다시 시도는 loadProjects를 호출합니다.'),('③ empty','데이터가 없거나 선택한 언어에 맞는 항목이 없습니다. 오류와 다른 정상적인 결과입니다.')])+box('<b>실험 화면과 검증을 구분합니다</b><p>위 캡처는 학습용 버튼으로 만든 가상 상태입니다. 별도로 실제 fetch 경로에 403·빈 배열·성공 응답을 테스트 도구로 주입해 오류 처리도 검사했습니다. 실제 인터넷 연결에서는 성공 응답을 확인했습니다.</p>'))
pages.append('<h1>07. 폼 검증은 작은 상태 관리</h1>'+fig('05-form-error.png','빈 폼을 확인했을 때 나타나는 실제 오류 화면.',[(1,49,17),(2,49,36),(3,49,54)])+'<div class="flow">submit / input → validate → state.errors → 오류 문구·테두리</div>'+table([('① 이름 · ③ 메시지','trim으로 앞뒤 공백을 제거한 값이 비어 있는지 검사합니다. 공백만 넣어도 필수값 검사를 통과하지 않습니다.'),('② 이메일','input type="email"의 validity.typeMismatch를 사용합니다. 형식 검사이며 실제 주소의 존재나 수신 가능성을 보장하지 않습니다.'),('오류와 초점','textContent로 각 오류를 표시하고 aria-invalid를 갱신합니다. 제출 실패 시 첫 오류 입력으로 초점을 옮깁니다.')])+code("event.preventDefault();\nconst results = fields.map(validate);\nif (results.every(Boolean)) {\n  // 입력 확인 성공 안내: 실제 전송은 하지 않음\n}")+ '<p class="small">실제 구현 위치: js/main.js의 validate와 contact-form submit 이벤트. novalidate는 브라우저의 기본 팝업을 끄고, 직접 만든 오류 문구를 보여주기 위해 사용합니다.</p>')
pages.append('<h1>08. 직접 확인하고 설명하기</h1>'+fig('06-form-success.png','유효한 값을 입력하면 확인 완료 안내가 나타납니다. 서버나 이메일로 전송하지 않습니다.',[(1,49,87)])+table([('내가 해볼 순서','① 모바일 메뉴 열기/닫기 → ② 테마 바꾸고 새로고침 → ③ 언어 필터 → ④ 로딩/오류/빈 상태 → ⑤ 잘못된 이메일 고치기.'),('예상 결과','메뉴 표시가 바뀌고, 테마는 유지되고, CSS 카드 1개가 보이고, 각 API 상태가 구분되고, 이메일 오류가 사라져야 합니다.'),('설명 연습','“어떤 이벤트가 시작점인가? 어떤 값이 달라졌나? 어느 함수가 어느 DOM을 바꾸나?”를 기능마다 말해보세요.')])+box('<b>실행 검증 결과</b><p>360/390/768/1024/1440px에서 가로 넘침 없음. 모바일 메뉴, 테마 저장, 폼 검사, 필터, 스크롤 버튼, HTTP 403·빈 결과·성공·외부 문자열 처리 통과. 실제 API 카드 8개. JavaScript 실행 오류 0개.</p><p>전체 접근성 인증이나 모든 브라우저 검증을 의미하지는 않습니다. GitHub Pages 공개 환경 검증은 아직 하지 않았습니다.</p>')+'<p class="small">캡처 원본: deliverables/screenshots/ · 검증 기록: deliverables/verification.json · 테스트 스크립트: scripts/capture.py. 코드 예시는 이해를 위해 일부를 발췌했으며 원본 파일을 함께 확인하세요.</p>')
doc('03-practice','실전 개념 적용',pages)
print('HTML documents generated:',len(list(D.glob('*.html'))))
